# Generated by Django 4.2.5 on 2023-09-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisdjango', '0002_rename_book_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.CharField(default='https://images-na.amazon.com/images/I/51y-88hU70L._SX325_BO1,204,203,200_.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
